// import { Navigation } from "@shared/ui";
import { Navigation } from '@shared/ui';
import '@style/globals.css';
import Script from 'next/script';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header style={{ width: '100%' }}>
          <Navigation />
        </header>
        <div
          id="container"
          style={{ display: 'flex', height: '100%', flexFlow: 'column nowrap' }}
        >
          {children}
        </div>
        <Script src="https://kit.fontawesome.com/a9f70cc687.js" />
      </body>
    </html>
  );
}
